//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceApp.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class dictionaries
    {
        public int idDict { get; set; }
        public string nameTable { get; set; }
        public string displayName { get; set; }
    }
}
