//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceApp.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class mos
    {
        public mos()
        {
            this.mos1 = new HashSet<mos>();
            this.specializations = new HashSet<specializations>();
        }
    
        public int idMO { get; set; }
        public string name { get; set; }
        public string fullName { get; set; }
        public Nullable<int> idChief { get; set; }
        public Nullable<int> parent { get; set; }
    
        public virtual ICollection<mos> mos1 { get; set; }
        public virtual mos mos2 { get; set; }
        public virtual persons persons { get; set; }
        public virtual ICollection<specializations> specializations { get; set; }
    }
}
