//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceApp.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class persons
    {
        public persons()
        {
            this.mos = new HashSet<mos>();
        }
    
        public int idPerson { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
    
        public virtual ICollection<mos> mos { get; set; }
    }
}
