//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceApp.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class specializations
    {
        public specializations()
        {
            this.specializations1 = new HashSet<specializations>();
            this.mos = new HashSet<mos>();
        }
    
        public int idSpec { get; set; }
        public string name { get; set; }
        public Nullable<int> parent { get; set; }
    
        public virtual ICollection<specializations> specializations1 { get; set; }
        public virtual specializations specializations2 { get; set; }
        public virtual ICollection<mos> mos { get; set; }
    }
}
